<?php
declare(strict_types=1);

function bee_species_data(): array
{
    return [
        [
            'slug' => 'abelha-do-mel',
            'common_name' => 'Abelha-do-mel',
            'scientific_name' => 'Apis mellifera',
            'image' => 'Apis mellifera - Wikipedia, la enciclopedia libre.jpg',
            'category' => 'Abelha social manejada',
            'distribution' => 'Criada em varias regioes do Brasil e do mundo',
            'role' => 'Producao de mel, cera e polinizacao agricola',
            'featured' => true,
            'intro' => 'Apis mellifera e a especie mais conhecida da apicultura, com colonias grandes, organizacao social complexa e forte importancia para a polinizacao de cultivos.',
            'overview_title' => 'Uma especie amplamente criada',
            'overview' => 'Essa abelha vive em colonias com rainha, operarias e zangoes. Sua capacidade de se adaptar a diferentes climas ajudou na difusao da especie em varias regioes.',
            'curiosity_title' => 'Uma referencia quando o assunto e mel',
            'curiosity' => 'A producao de mel e cera tornou a abelha-do-mel uma das especies mais estudadas e manejadas. Ao mesmo tempo, ela participa da polinizacao de muitas plantas cultivadas.',
            'care_title' => 'Ambiente equilibrado fortalece as colonias',
            'care' => 'Paisagens com flores ao longo do ano, agua limpa e menos pressao de agrotoxicos ajudam a manter enxames mais saudaveis e ativos.',
        ],
        [
            'slug' => 'abelha-verde-metalica',
            'common_name' => 'Abelha-verde-metalica',
            'scientific_name' => 'Augochloropsis',
            'image' => 'Metallic Green Bee #3.jpg',
            'category' => 'Abelha nativa de brilho metalico',
            'distribution' => 'Americas, inclusive varios ambientes brasileiros',
            'role' => 'Polinizacao de flores nativas e jardins',
            'featured' => false,
            'intro' => 'Augochloropsis reune abelhas pequenas e muito marcantes pelo brilho verde ou azulado, frequentemente vistas em flores abertas e areas ensolaradas.',
            'overview_title' => 'Cor intensa e tamanho discreto',
            'overview' => 'Esse grupo pertence a familia Halictidae e chama atencao pela coloracao metalica. Apesar do porte menor, participa ativamente da visita a flores e da coleta de polen.',
            'curiosity_title' => 'Brilho que vira identidade visual',
            'curiosity' => 'As abelhas verde-metalicas costumam ser lembradas pelo reflexo do corpo quando a luz bate nas asas e no torax, tornando a observacao em campo ainda mais interessante.',
            'care_title' => 'Flores variadas ajudam esse grupo',
            'care' => 'Jardins com especies nativas, menos perturbacao no solo e diversidade de floradas favorecem a permanencia dessas abelhas em areas urbanas e rurais.',
        ],
        [
            'slug' => 'mamangava-preta',
            'common_name' => 'Mamangava-preta',
            'scientific_name' => 'Bombus morio',
            'image' => 'Mamangava-preta.jpg',
            'category' => 'Mamangava nativa',
            'distribution' => 'Brasil e outras areas da America do Sul',
            'role' => 'Polinizacao por vibracao em varias plantas',
            'featured' => false,
            'intro' => 'Bombus morio e uma mamangava robusta, de voo forte e grande valor para flores que dependem da vibracao para liberar polen.',
            'overview_title' => 'Grande porte e visita marcante',
            'overview' => 'Essa especie aparece em jardins, bordas de mata e areas abertas. O corpo maior e o ritmo de voo ajudam a explicar por que ela chama tanta atencao nas floradas.',
            'curiosity_title' => 'Especialista em buzz pollination',
            'curiosity' => 'A mamangava-preta consegue vibrar flores para soltar polen, um comportamento importante em especies vegetais que dependem desse tipo de visita.',
            'care_title' => 'Abrigo e flores nativas fazem diferenca',
            'care' => 'Paisagens com diversidade floral e locais adequados para nidificacao ajudam a manter a atividade dessa mamangava ao longo das estacoes.',
        ],
        [
            'slug' => 'abelha-da-acerola',
            'common_name' => 'Abelha-da-acerola',
            'scientific_name' => 'Centris analis',
            'image' => 'centris analis.jpg',
            'category' => 'Abelha solitaria coletora de oleos',
            'distribution' => 'Brasil, America Central e outras areas tropicais',
            'role' => 'Polinizacao eficiente de acerola e outras flores',
            'featured' => false,
            'intro' => 'Centris analis e uma abelha nativa de voo rapido, muito estudada por sua eficiencia na polinizacao da acerola e por usar cavidades para nidificar.',
            'overview_title' => 'Uma polinizadora valiosa para pomares',
            'overview' => 'Ao contrario das abelhas sociais, cada femea constroi e abastece o proprio ninho. Isso nao diminui sua importancia agricola, especialmente em areas de cultivo de acerola.',
            'curiosity_title' => 'Oleos florais entram na rotina da especie',
            'curiosity' => 'Centris analis busca recursos em plantas que oferecem oleos florais, um comportamento que a torna muito ligada a certos grupos de flores nativas.',
            'care_title' => 'Cavidades e flora de apoio fortalecem a especie',
            'care' => 'Disponibilizar ninhos-armadilha, madeira com cavidades e floradas ao redor pode favorecer a presenca dessa abelha em sistemas produtivos.',
        ],
        [
            'slug' => 'moca-branca',
            'common_name' => 'Moca-branca',
            'scientific_name' => 'Frieseomelitta doederleini',
            'image' => 'Apis mellifera ligustica  (abelha italiana).jpg',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Brasil, com destaque para regioes quentes',
            'role' => 'Polinizacao de vegetacao nativa e quintais',
            'featured' => false,
            'intro' => 'Frieseomelitta doederleini e uma abelha sem ferrao valorizada na meliponicultura e reconhecida por formar colonias sociais bastante organizadas.',
            'overview_title' => 'Pequena, social e importante',
            'overview' => 'A moca-branca vive em colonias e participa da polinizacao de varias plantas nativas. O manejo cuidadoso ajuda a manter o equilibrio dos ninhos.',
            'curiosity_title' => 'Especie lembrada pela docilidade',
            'curiosity' => 'Muitos criadores valorizam essa abelha pelo comportamento relativamente tranquilo e pela adaptacao a caixas de manejo em projetos de conservacao.',
            'care_title' => 'Protecao da flora local e fundamental',
            'care' => 'A especie depende de oferta continua de flores, abrigo e menos disturbio ambiental para manter colonias saudaveis e ativas.',
        ],
        [
            'slug' => 'manduri-do-mato-grosso',
            'common_name' => 'Manduri-do-Mato-Grosso',
            'scientific_name' => 'Melipona orbignyi',
            'image' => 'transferir (1).jpg',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Centro-Oeste brasileiro e areas proximas',
            'role' => 'Polinizacao de plantas nativas e frutiferas',
            'featured' => false,
            'intro' => 'Melipona orbignyi e uma meliponinea nativa conhecida como manduri-do-Mato-Grosso, associada a paisagens onde a flora local ainda sustenta boas floradas.',
            'overview_title' => 'Uma especie ligada ao bioma regional',
            'overview' => 'Essa abelha pertence ao grupo das Melipona, reunindo colonias sociais e grande valor para a biodiversidade local. Sua ocorrencia ajuda a mostrar a riqueza das abelhas nativas.',
            'curiosity_title' => 'Meliponicultura e observacao caminham juntas',
            'curiosity' => 'Especies como a manduri chamam atencao por unir interesse de criadores, valor ecologico e potencial educativo em projetos de conservacao.',
            'care_title' => 'Vegetacao preservada sustenta o ciclo',
            'care' => 'Corredores de vegetacao, sombra adequada e oferta de flores nativas fortalecem a manutencao dos ninhos e a atividade polinizadora.',
        ],
        [
            'slug' => 'mandacaia',
            'common_name' => 'Mandacaia',
            'scientific_name' => 'Melipona quadrifasciata',
            'image' => 'Melipona_quadrifasciata.jpeg',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Brasil, sobretudo Sudeste e Sul',
            'role' => 'Polinizacao e meliponicultura',
            'featured' => true,
            'intro' => 'Melipona quadrifasciata e uma das abelhas sem ferrao mais conhecidas do Brasil, famosa pelas faixas claras no abdomen e pelo mel muito apreciado.',
            'overview_title' => 'Uma das estrelas da meliponicultura',
            'overview' => 'A mandacaia forma colonias sociais e costuma ser lembrada em projetos de criacao racional, educacao ambiental e conservacao de abelhas nativas.',
            'curiosity_title' => 'As faixas do abdomen viram assinatura visual',
            'curiosity' => 'O padrao listrado e um dos detalhes que ajudam na identificacao da especie, tornando a mandacaia bastante reconhecida entre visitantes e criadores.',
            'care_title' => 'Caixas bem manejadas e flora diversa ajudam',
            'care' => 'A especie responde melhor quando encontra abrigo protegido, menos variacao brusca no ambiente e floradas variadas durante o ano.',
        ],
        [
            'slug' => 'urucu-amarela',
            'common_name' => 'Urucu-amarela',
            'scientific_name' => 'Melipona rufiventris',
            'image' => 'Abelhas sem ferrão_ Uruçu-Amarela (Melipona rufiventris).jpg',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Brasil, com ocorrencias em areas de mata e cerrado',
            'role' => 'Polinizacao de vegetacao nativa',
            'featured' => false,
            'intro' => 'Melipona rufiventris e uma abelha sem ferrao muito valorizada pela beleza, pelo valor ecologico e pela relacao com a meliponicultura brasileira.',
            'overview_title' => 'Especie social de grande interesse',
            'overview' => 'A urucu-amarela forma colonias bem estruturadas e participa da polinizacao de diversas plantas, reforcando o equilibrio de ecossistemas nativos.',
            'curiosity_title' => 'Tambem conhecida por nomes regionais',
            'curiosity' => 'Em algumas regioes a especie recebe outras denominacoes populares, o que mostra como as abelhas nativas fazem parte da cultura local.',
            'care_title' => 'Conservacao e manejo precisam caminhar juntos',
            'care' => 'A manutencao dessa especie depende de ambientes floridos, disponibilidade de abrigo e cuidado com a retirada inadequada de ninhos da natureza.',
        ],
        [
            'slug' => 'urucu-nordestina',
            'common_name' => 'Urucu-nordestina',
            'scientific_name' => 'Melipona scutellaris',
            'image' => 'Abelhas sem ferrão_ Uruçu (Melipona scutellaris).jpg',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Nordeste do Brasil',
            'role' => 'Polinizacao e importancia cultural regional',
            'featured' => false,
            'intro' => 'Melipona scutellaris e uma das abelhas sem ferrao mais valorizadas do Nordeste, reconhecida pelo mel e pela forte ligacao com a cultura regional.',
            'overview_title' => 'Uma referencia nordestina entre as meliponas',
            'overview' => 'Essa especie vive em colonias sociais e e muito lembrada em iniciativas de preservacao, producao racional de mel e educacao ambiental.',
            'curiosity_title' => 'Mel bastante apreciado',
            'curiosity' => 'O mel da urucu-nordestina costuma ser citado como um dos mais valorizados entre as abelhas sem ferrao, somando importancia economica e cultural.',
            'care_title' => 'Protecao dos remanescentes e essencial',
            'care' => 'Florestas, quintais produtivos e sistemas agroflorestais podem contribuir para a manutencao dessa especie em varias paisagens do Nordeste.',
        ],
        [
            'slug' => 'boca-de-sapo',
            'common_name' => 'Boca-de-sapo',
            'scientific_name' => 'Partamona helleri',
            'image' => 'Partamona helleri.jpg',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Brasil e outras areas tropicais da America do Sul',
            'role' => 'Polinizacao de ambientes naturais e urbanos',
            'featured' => false,
            'intro' => 'Partamona helleri e famosa pela entrada de ninho muito caracteristica, que ajuda a explicar o nome popular boca-de-sapo.',
            'overview_title' => 'Uma abelha nativa de identidade marcante',
            'overview' => 'A especie forma colonias sociais e pode ser observada em diferentes ambientes, sempre com destaque para a arquitetura da entrada do ninho.',
            'curiosity_title' => 'O ninho vira sinal de reconhecimento',
            'curiosity' => 'Muitas pessoas identificam essa abelha primeiro pela forma do ninho, antes mesmo de notar os detalhes do corpo e do comportamento.',
            'care_title' => 'Estruturas de abrigo merecem respeito',
            'care' => 'Evitar remocao sem necessidade e preservar arvores, muros e locais usados como suporte ajuda a manter as colonias ativas.',
        ],
        [
            'slug' => 'abelha-mirim',
            'common_name' => 'Abelha-mirim',
            'scientific_name' => 'Plebeia droryana',
            'image' => 'Plebeia droryana.webp',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Sul e Sudeste do Brasil',
            'role' => 'Polinizacao de flores pequenas e quintais',
            'featured' => false,
            'intro' => 'Plebeia droryana e uma pequena abelha sem ferrao muito adaptada a cavidades e bastante presente em projetos de meliponicultura urbana.',
            'overview_title' => 'Pequena no tamanho, grande no valor',
            'overview' => 'Mesmo discreta, a abelha-mirim ajuda na polinizacao de plantas nativas e ornamentais. Seu porte reduzido nao diminui sua importancia ecologica.',
            'curiosity_title' => 'Boa adaptacao a ambientes urbanos',
            'curiosity' => 'A especie pode ocupar cavidades em estruturas humanas e se manter em quintais com flores, o que facilita sua observacao em cidades.',
            'care_title' => 'Jardins floridos sao aliados',
            'care' => 'Manter flores de diferentes epocas, agua limpa e abrigo protegido ajuda a favorecer populacoes saudaveis dessa pequena meliponinea.',
        ],
        [
            'slug' => 'mandaguari',
            'common_name' => 'Mandaguari',
            'scientific_name' => 'Scaptotrigona postica',
            'image' => 'Caupolicana fulvicollis, Female, bees of Chile.jpg',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Florestas e areas abertas do Brasil',
            'role' => 'Polinizacao de varias especies vegetais',
            'featured' => false,
            'intro' => 'Scaptotrigona postica, conhecida em muitas regioes como mandaguari, e uma abelha social importante para a polinizacao de ambientes tropicais.',
            'overview_title' => 'Especie muito presente na fauna nativa',
            'overview' => 'A mandaguari forma colonias fortes, com atividade intensa nas floradas. Seu comportamento social faz dela uma das especies mais lembradas entre as sem ferrao.',
            'curiosity_title' => 'Visitante frequente de floradas variadas',
            'curiosity' => 'A especie aparece em diferentes tipos de vegetacao e ajuda a conectar a polinizacao entre plantas cultivadas e nativas.',
            'care_title' => 'Paisagens com continuidade floral favorecem a especie',
            'care' => 'Quanto maior a oferta de flores e a preservacao do entorno, maiores as chances de manter ninhos ativos e produtivos.',
        ],
        [
            'slug' => 'jatai',
            'common_name' => 'Jatai',
            'scientific_name' => 'Tetragonisca angustula',
            'image' => 'Tetragonisca angustula, Costa Rica.jpg',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'America Latina, inclusive varias cidades brasileiras',
            'role' => 'Polinizacao de plantas nativas, hortas e jardins',
            'featured' => false,
            'intro' => 'Tetragonisca angustula e uma das menores e mais populares abelhas sem ferrao, muito conhecida pela docilidade e pela adaptacao a ambientes urbanos.',
            'overview_title' => 'Pequena, social e muito querida',
            'overview' => 'A jatai costuma aparecer em projetos educativos, criacoes urbanas e quintais floridos. Seu tamanho reduzido facilita a convivencia com pessoas.',
            'curiosity_title' => 'A entrada do ninho e um detalhe famoso',
            'curiosity' => 'Muitos ninhos exibem um pequeno tubo de cerume na entrada, um traço visual facilmente associado a essa especie.',
            'care_title' => 'Caixas protegidas e floradas constantes ajudam',
            'care' => 'Boa ventilacao, sombra moderada e diversidade floral ao redor deixam o ambiente mais favoravel para o desenvolvimento da colonia.',
        ],
        [
            'slug' => 'jatai-do-sul',
            'common_name' => 'Jatai-do-sul',
            'scientific_name' => 'Tetragonisca fiebrigi',
            'image' => 'Tetragonisca angustula en flor de Tithonia diversifolia.jpg',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Sul do Brasil e outras areas ao sul da America do Sul',
            'role' => 'Polinizacao de plantas nativas e ornamentais',
            'featured' => false,
            'intro' => 'Tetragonisca fiebrigi e muito parecida com a jatai comum, mas se destaca pela distribuicao mais ao sul e pelo valor para ecossistemas regionais.',
            'overview_title' => 'Uma prima proxima da jatai comum',
            'overview' => 'Essa especie tambem forma colonias sociais e pode ser mantida em sistemas de observacao e manejo, desde que o ambiente respeite suas necessidades.',
            'curiosity_title' => 'Semelhanca com a jatai confunde muita gente',
            'curiosity' => 'A comparacao entre jatai e jatai-do-sul e um bom exemplo de como especies proximas exigem observacao cuidadosa para identificacao correta.',
            'care_title' => 'Clima e abrigo influenciam bastante',
            'care' => 'Proteger os ninhos de extremos climaticos e garantir floradas locais ajuda no bom desempenho dessa especie em regioes mais frias.',
        ],
        [
            'slug' => 'irapua',
            'common_name' => 'Irapua',
            'scientific_name' => 'Trigona spinipes',
            'image' => 'Abelhas sem ferrão_ Irapuã (Trigona spinipes).jpg',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Grande parte do Brasil',
            'role' => 'Polinizacao e interacao intensa com varios ambientes',
            'featured' => false,
            'intro' => 'Trigona spinipes e uma abelha sem ferrao muito conhecida pelo comportamento defensivo e pelos ninhos externos de grande porte.',
            'overview_title' => 'Uma especie muito ativa e adaptavel',
            'overview' => 'A irapua aparece em diversos ambientes e costuma ser facilmente notada pela movimentacao constante ao redor do ninho e das plantas visitadas.',
            'curiosity_title' => 'Defesa intensa faz parte da fama',
            'curiosity' => 'Mesmo sem ferrrao, a especie pode morder e se prender em pelos e roupas, o que explica a reputacao de abelha mais brava em algumas regioes.',
            'care_title' => 'Convivencia pede manejo consciente',
            'care' => 'Em vez de destruir ninhos por impulso, o ideal e avaliar cada caso com cuidado e considerar tecnicas adequadas de manejo e realocacao quando necessario.',
        ],
        [
            'slug' => 'abelha-carpinteira-violeta',
            'common_name' => 'Abelha-carpinteira-violeta',
            'scientific_name' => 'Xylocopa augusti',
            'image' => 'Xylocopa augusti.jpg',
            'category' => 'Abelha carpinteira',
            'distribution' => 'America do Sul',
            'role' => 'Polinizacao de flores grandes e vistosas',
            'featured' => false,
            'intro' => 'Xylocopa augusti e uma grande abelha carpinteira sul-americana, conhecida pelo corpo robusto, asas escuras e brilho violeta.',
            'overview_title' => 'Forca, tamanho e ninho em madeira',
            'overview' => 'As abelhas carpinteiras costumam usar madeira para construir ninhos. O voo forte e o porte maior fazem dessa especie uma visitante impressionante nas floradas.',
            'curiosity_title' => 'As asas escuras criam um visual unico',
            'curiosity' => 'Quando a luz atinge as asas, o reflexo violeta destaca ainda mais a presenca da especie e ajuda a explicar seu apelo visual.',
            'care_title' => 'Madeira e flores sao parte do ciclo',
            'care' => 'Preservar areas com oferta floral e locais adequados para nidificacao ajuda a manter as populacoes dessa abelha em atividade.',
        ],
        [
            'slug' => 'abelha-carpinteira-do-ceara',
            'common_name' => 'Abelha-carpinteira-do-Ceara',
            'scientific_name' => 'Xylocopa cearensis',
            'image' => 'xylocopa violacea.jpg',
            'category' => 'Abelha carpinteira',
            'distribution' => 'Brasil, com destaque para areas quentes e secas',
            'role' => 'Polinizacao de plantas nativas e cultivadas',
            'featured' => true,
            'intro' => 'Xylocopa cearensis e uma abelha carpinteira brasileira de grande porte, ligada ao habito de perfurar madeira para formar ninhos.',
            'overview_title' => 'Uma especie robusta e muito adaptada',
            'overview' => 'Assim como outras Xylocopa, essa abelha se destaca pelo voo potente e pela capacidade de explorar flores maiores em diferentes paisagens.',
            'curiosity_title' => 'Nidificacao em madeira marca o grupo',
            'curiosity' => 'A relacao com troncos, mourões e outras estruturas lenhosas ajuda a entender por que as abelhas carpinteiras costumam ser tao lembradas.',
            'care_title' => 'Menos remocao e mais observacao',
            'care' => 'Conservar locais de nidificacao e evitar disturbios desnecessarios e uma forma importante de proteger essas grandes polinizadoras.',
        ],
        [
            'slug' => 'centris-klugii',
            'common_name' => 'Abelha-de-oleo klugii',
            'scientific_name' => 'Centris klugii',
            'image' => 'Centris klugii.jpg',
            'category' => 'Abelha solitaria coletora de oleos',
            'distribution' => 'Regioes tropicais da America do Sul',
            'role' => 'Polinizacao de flores nativas, especialmente oleiferas',
            'featured' => false,
            'intro' => 'Centris klugii pertence ao grupo das abelhas Centris, conhecidas pela coleta de oleos florais e pela importancia na polinizacao de plantas nativas.',
            'overview_title' => 'Uma representante do grupo Centris',
            'overview' => 'Como outras especies proximas, essa abelha tende a usar recursos florais muito especificos e depende de cavidades ou substratos adequados para reproduzir.',
            'curiosity_title' => 'Relacao estreita com certas flores',
            'curiosity' => 'As Centris costumam ser lembradas pela habilidade de coletar oleos em vez de apenas nectar, o que torna sua ecologia bastante particular.',
            'care_title' => 'Conservar flora nativa e essencial',
            'care' => 'A preservacao de plantas fornecedoras de oleo e de locais de nidificacao ajuda a manter a presenca da especie em paisagens produtivas e naturais.',
        ],
        [
            'slug' => 'euglossa-cordata',
            'common_name' => 'Abelha-das-orquideas',
            'scientific_name' => 'Euglossa cordata',
            'image' => 'Euglossa cordata.jpg',
            'category' => 'Abelha das orquideas',
            'distribution' => 'America tropical, inclusive varias areas do Brasil',
            'role' => 'Polinizacao de flores aromaticas e orquideas',
            'featured' => true,
            'intro' => 'Euglossa cordata e uma abelha conhecida pelo brilho metalico e pela relacao com flores aromaticas, especialmente no grupo das orquideas.',
            'overview_title' => 'Beleza metalica e comportamento sofisticado',
            'overview' => 'Essa especie faz parte de um grupo muito estudado por sua interacao com fragrancias florais. O resultado e uma combinacao de valor ecologico e forte apelo visual.',
            'curiosity_title' => 'Machos coletam aromas',
            'curiosity' => 'Nos euglossineos, os machos podem coletar compostos aromaticos de flores e outras fontes, um comportamento famoso entre observadores de abelhas.',
            'care_title' => 'Matas e jardins ricos em flores ajudam',
            'care' => 'Ambientes com boa diversidade floral e fragmentos vegetados ampliam as chances de manter essa especie visitando o local ao longo do ano.',
        ],
        [
            'slug' => 'exomalopsis-vernoniae',
            'common_name' => 'Abelha-nativa vernoniae',
            'scientific_name' => 'Exomalopsis vernoniae',
            'image' => 'Exomalopsis vernoniae.jpg',
            'category' => 'Abelha nativa de pequeno porte',
            'distribution' => 'America do Sul, em ambientes floridos',
            'role' => 'Polinizacao de vegetacao nativa',
            'featured' => false,
            'intro' => 'Exomalopsis vernoniae representa um grupo de abelhas nativas discretas, mas importantes para a manutencao da polinizacao em plantas de pequeno e medio porte.',
            'overview_title' => 'Pequena e funcional na paisagem',
            'overview' => 'Especies desse grupo costumam passar despercebidas quando comparadas a abelhas maiores, mas seguem cumprindo um papel essencial na visita a flores.',
            'curiosity_title' => 'Nem toda polinizadora precisa ser grande',
            'curiosity' => 'A observacao de especies menores ajuda a ampliar a percepcao sobre a diversidade real de abelhas e sobre quantas formas de vida sustentam as floradas.',
            'care_title' => 'Menos impacto, mais diversidade',
            'care' => 'Reducao de agrotoxicos, manejo cuidadoso do solo e presenca de flores nativas sao medidas que beneficiam esse tipo de abelha.',
        ],
        [
            'slug' => 'melipona-bicolor',
            'common_name' => 'Guaraipo',
            'scientific_name' => 'Melipona bicolor',
            'image' => 'Melipona bicolor.webp',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Mata Atlantica e regioes do Sul e Sudeste',
            'role' => 'Polinizacao de flora nativa e sistemas produtivos',
            'featured' => false,
            'intro' => 'Melipona bicolor e uma abelha sem ferrao brasileira bastante importante para remanescentes florestais e para projetos de conservacao das meliponas.',
            'overview_title' => 'Uma melipona ligada a ambientes florestais',
            'overview' => 'A especie forma colonias sociais e depende de boa oferta de abrigo e recursos florais para manter o ciclo de producao e desenvolvimento.',
            'curiosity_title' => 'Abelhas sem ferrao tambem variam bastante entre si',
            'curiosity' => 'Comparar especies do mesmo genero mostra como tamanho, comportamento e preferencias ambientais podem mudar mesmo dentro de grupos proximos.',
            'care_title' => 'Fragmentos de mata sao aliados',
            'care' => 'Conservar arvores, cavidades naturais e floradas em volta dos ninhos ajuda a favorecer a permanencia dessa especie.',
        ],
        [
            'slug' => 'melipona-rufiventris',
            'common_name' => 'Uruçu-amarela',
            'scientific_name' => 'Melipona rufiventris',
            'image' => 'Melipona rufiventris.jpg',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Brasil central e sudeste, em paisagens nativas',
            'role' => 'Polinizacao de flora regional',
            'featured' => false,
            'intro' => 'Melipona rufiventris aparece aqui como um registro cientifico da especie, ampliando a colecao com outra entrada visual para essa importante melipona brasileira.',
            'overview_title' => 'Registro cientifico da urucu-amarela',
            'overview' => 'Mesmo ja representada por nome popular, a inclusao do nome cientifico ajuda a organizar melhor a colecao e a leitura das especies sob diferentes referencias.',
            'curiosity_title' => 'Nome comum e nome cientifico convivem no atlas',
            'curiosity' => 'No universo das abelhas, a mesma especie pode ser conhecida por varios nomes locais. Isso torna o catalogo mais rico e tambem mais desafiador de organizar.',
            'care_title' => 'Valorizar a identificacao correta tambem e conservar',
            'care' => 'Quanto melhor a identificacao das especies, mais facil fica orientar criacao, observacao, pesquisa e protecao dos ambientes onde elas vivem.',
        ],
        [
            'slug' => 'plebeia-nigriceps',
            'common_name' => 'Mirim-nigriceps',
            'scientific_name' => 'Plebeia nigriceps',
            'image' => 'Plebeia nigriceps.webp',
            'category' => 'Abelha sem ferrao',
            'distribution' => 'Brasil, especialmente em areas vegetadas',
            'role' => 'Polinizacao de flores pequenas e nativas',
            'featured' => false,
            'intro' => 'Plebeia nigriceps e uma pequena abelha sem ferrao que ajuda a mostrar como especies discretas sustentam grande parte da dinamica das floradas.',
            'overview_title' => 'Uma meliponinea de menor porte',
            'overview' => 'Assim como outras Plebeia, essa especie tende a aproveitar cavidades para ninho e pode ter boa relacao com ambientes manejados de forma cuidadosa.',
            'curiosity_title' => 'As pequenas tambem merecem protagonismo',
            'curiosity' => 'Catalogar especies de menor tamanho enriquece o projeto e convida o visitante a olhar para detalhes que costumam passar despercebidos.',
            'care_title' => 'Estruturas pequenas importam muito',
            'care' => 'Preservar cavidades, muros, troncos e pequenos refegios pode fazer diferenca para a permanencia dessas abelhas no ambiente.',
        ],
        [
            'slug' => 'ptilothrix-fructifera',
            'common_name' => 'Abelha-de-oleo fructifera',
            'scientific_name' => 'Ptilothrix fructifera',
            'image' => 'Ptilothrix fructifera.jpg',
            'category' => 'Abelha solitaria nativa',
            'distribution' => 'Ambientes secos e abertos da America do Sul',
            'role' => 'Polinizacao de flores especificas',
            'featured' => false,
            'intro' => 'Ptilothrix fructifera e uma abelha nativa associada a nichos ecologicos especificos, reforcando como a diversidade de polinizadores vai muito alem das especies mais conhecidas.',
            'overview_title' => 'Uma especie para ampliar o atlas',
            'overview' => 'Esse tipo de registro ajuda o site a ficar mais completo, incluindo abelhas menos populares, mas igualmente relevantes para a biodiversidade.',
            'curiosity_title' => 'Cada nova especie muda o olhar sobre o conjunto',
            'curiosity' => 'Ao adicionar especies menos famosas, o projeto passa a mostrar melhor a variedade de formas, tamanhos e estrategias de vida das abelhas.',
            'care_title' => 'Conhecimento tambem e ferramenta de conservacao',
            'care' => 'Mapear e divulgar especies menos conhecidas ajuda a valorizar seus ambientes e reforca a importancia da pesquisa e da observacao de campo.',
        ],
        [
            'slug' => 'centris-aenea',
            'common_name' => 'Abelha-de-oleo',
            'scientific_name' => 'Centris aenea',
            'image' => 'Centris aenea.jpg',
            'category' => 'Abelha solitaria coletora de oleos',
            'distribution' => 'Brasil e outras areas tropicais da America do Sul',
            'role' => 'Polinizacao de acerola, malpighiaceas e flora nativa',
            'featured' => false,
            'intro' => 'Centris aenea e uma abelha nativa muito associada a flores que oferecem oleos, sendo lembrada pelo valor na polinizacao e pelo voo rapido e firme.',
            'overview_title' => 'Uma das abelhas-de-oleo mais lembradas',
            'overview' => 'Essa especie integra um grupo importante de abelhas solitarias que usam oleos florais na rotina reprodutiva. Sua presenca reforca a riqueza das polinizadoras nativas brasileiras.',
            'curiosity_title' => 'Tambem aparece ligada a pomares',
            'curiosity' => 'Centris aenea pode ser uma boa visitante de culturas como a acerola, o que aproxima a especie tanto da conservacao quanto do interesse agricola.',
            'care_title' => 'Solo, cavidades e flora nativa ajudam a especie',
            'care' => 'Ambientes com diversidade floral, menos degradacao do solo e oferta de locais de nidificacao favorecem a permanencia dessa abelha.',
        ],
        [
            'slug' => 'oxytrigona-tataira',
            'common_name' => 'Tataira',
            'scientific_name' => 'Oxytrigona tataira',
            'image' => 'Oxytrigona tataira.jpg',
            'category' => 'Abelha sem ferrao defensiva',
            'distribution' => 'Brasil e outras areas da America tropical',
            'role' => 'Polinizacao e destaque comportamental entre meliponineos',
            'featured' => true,
            'intro' => 'Oxytrigona tataira, mais conhecida como tataira, e uma abelha sem ferrao famosa pelo comportamento defensivo intenso e pela forte identidade popular.',
            'overview_title' => 'Uma especie que chama atencao pelo comportamento',
            'overview' => 'Embora faca parte do grupo das sem ferrao, a tataira se destaca pela defesa agressiva do ninho, o que a tornou uma das abelhas mais comentadas entre criadores e observadores.',
            'curiosity_title' => 'Abelha-de-fogo em varios lugares',
            'curiosity' => 'A especie tambem pode aparecer com apelidos como abelha-de-fogo ou cospe-fogo, nomes ligados a ardencia provocada pela secrecao usada na defesa.',
            'care_title' => 'Observacao deve ser feita com distancia e respeito',
            'care' => 'Por ser uma especie defensiva, o ideal e evitar perturbacoes proximas ao ninho e valorizar o manejo por quem conhece bem o comportamento dela.',
        ],
        [
            'slug' => 'parapsaenythia-serripes',
            'common_name' => 'Abelha-solitaria serripes',
            'scientific_name' => 'Parapsaenythia serripes',
            'image' => 'Parapsaenythia serripes.jpg',
            'category' => 'Abelha solitaria nativa',
            'distribution' => 'Ambientes abertos e floridos da America do Sul',
            'role' => 'Polinizacao de plantas nativas de pequeno e medio porte',
            'featured' => false,
            'intro' => 'Parapsaenythia serripes amplia o atlas com um perfil mais raro e menos conhecido pelo grande publico, mas importante para mostrar a diversidade real das abelhas nativas.',
            'overview_title' => 'Uma especie menos famosa, mas valiosa',
            'overview' => 'Abelhas solitarias como essa ajudam a revelar quantas estrategias diferentes de vida existem dentro do grupo das abelhas brasileiras.',
            'curiosity_title' => 'Nem sempre o nome popular esta consolidado',
            'curiosity' => 'Algumas especies sao muito mais citadas pelo nome cientifico do que por um nome popular unico, o que mostra como ainda ha espaco para divulgacao e estudo.',
            'care_title' => 'Conhecer melhor e a melhor forma de proteger',
            'care' => 'Valorizar a observacao, os registros e a conservacao das floradas locais ajuda a manter especies menos conhecidas presentes na paisagem.',
        ],
    ];
}

function bee_find_species(string $slug): ?array
{
    foreach (bee_species_data() as $species) {
        if ($species['slug'] === $slug) {
            return $species;
        }
    }

    return null;
}

function bee_encode_path(string ...$segments): string
{
    return implode('/', array_map('rawurlencode', $segments));
}

function bee_wikipedia_url(array $species): string
{
    $directUrls = [
        'abelha-do-mel' => 'https://pt.wikipedia.org/wiki/Apis_mellifera',
        'mamangava-preta' => 'https://en.wikipedia.org/wiki/Bombus_morio',
        'abelha-da-acerola' => 'https://pt.wikipedia.org/wiki/Centris_analis',
        'mandacaia' => 'https://en.wikipedia.org/wiki/Melipona_quadrifasciata',
        'melipona-bicolor' => 'https://pt.wikipedia.org/wiki/Uru%C3%A7u-p%C3%A9-de-pau',
        'oxytrigona-tataira' => 'https://pt.wikipedia.org/wiki/Tata%C3%ADra',
        'plebeia-nigriceps' => 'https://pt.wikipedia.org/wiki/Plebeia_nigriceps',
    ];

    if (isset($directUrls[$species['slug']])) {
        return $directUrls[$species['slug']];
    }

    return 'https://pt.wikipedia.org/wiki/Especial:Pesquisar?search=' . rawurlencode($species['scientific_name']);
}
